### PR TITLE
Add new beautiful color schemes

### PR DESCRIPTION
**Pull request by dfcreative**
Hi @bpostlethwaite!

I’ve implemented the colormaps mentioned in #5.
There are compressed versions of them, original maps have 256 steps each, here the number of steps is reduced to 32, the tests in `draw.js` show that this is a good balance between size and veritability.

There is a bunch of new files, mostly source colormaps and `draw.js` script comparing compressed/original colormaps. I’ve whitelisted `index.js` and `colorScales.js`, so that should not be a trouble for npm users.

Please have a look and merge/publish to npm if everything is ok.

Looking forward to play with new maps in gl-spectrum :)

Thanks!

### CODE REVIEW

**Comment by bpostlethwaite** [comment]
Excellent - I will thoroughly review this week / weekend. Thanks for the PR!

**Comment by dfcreative** [comment]
Hi Ben! Is there any news on that?
@bpostlethwaite

**Comment by dfcreative** [comment]
@bpostlethwaite I temporarily used my fork [here](https://audio-lab.github.io/gl-spectrum), should say some schemes are quite nice, especially _cmocean_. But I did not manage to craft coefs to render each scheme beautifully. Anyways, looking forward.

**Comment by bpostlethwaite** [comment]
hey @dfcreative sorry I have been swamped recently. I'll check this out this week.

**Comment by dfcreative** [comment]
@bpostlethwaite any news?

**Comment by dfcreative** [comment]
@bpostlethwaite technically I can remove `draw.js` and all the colormap samples info from the PR to simplify review. Thought they do not affect installed package at all.

**Comment by bpostlethwaite** [comment]
aight reviewing right now!

**Comment by bpostlethwaite** [comment]
seems pretty good to me! There are some unnecessary changes considering we are just updating colour maps but I don't have objections.

**Comment by bpostlethwaite** [comment]
Thanks again and sorry for the delay

**Comment by dfcreative** [comment]
@bpostlethwaite Could you also publish minor update to npm?
Thanks!

**Comment by bpostlethwaite** [comment]
done https://www.npmjs.com/package/colormap

**Pull request merged**
